In [1]:
import pandas as pd
df=pd.read_csv('./Dataset_04.csv')

In [2]:
df

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five,runs_x
0,England,West Indies,London,124,23,6,7.670103,29.0,161
1,Afghanistan,Sri Lanka,Kolkata,47,60,7,4.700000,15.0,153
2,Australia,India,Mumbai,77,62,8,7.965517,41.0,166
3,New Zealand,Sri Lanka,Pallekele,59,44,3,4.657895,39.0,74
4,New Zealand,South Africa,Durban,132,20,5,7.920000,33.0,151
...,...,...,...,...,...,...,...,...,...
38472,South Africa,England,Cape Town,154,12,7,8.555556,64.0,191
38473,Bangladesh,West Indies,Lauderhill,48,76,8,6.545455,35.0,171
38474,South Africa,India,Nottingham,72,55,8,6.646154,26.0,130
38475,India,Australia,Colombo,56,81,9,8.615385,46.0,140
38476,South Africa,England,Cape Town,103,31,7,6.943820,38.0,191

In [3]:
# Now Doing train-test split. 
#This is Regression problem.
#output feature= runs_x(how much scored at the end).

In [4]:
df.sample(2)

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five,runs_x
25099,South Africa,England,Centurion,76,80,10,11.400000,63.0,222
4320,Sri Lanka,England,Chittagong,120,35,9,8.470588,57.0,189

In [5]:
X=df.drop(columns=['runs_x'])
Y=df['runs_x']

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [8]:
X_train

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five
20628,Pakistan,Bangladesh,St Lucia,54,79,10,7.902439,36.0
4564,India,Sri Lanka,Mirpur,111,24,8,6.937500,45.0
19086,India,New Zealand,Hamilton,168,4,5,8.689655,46.0
35544,India,England,Colombo,70,66,9,7.777778,36.0
27286,India,South Africa,Colombo,61,65,7,6.654545,32.0
...,...,...,...,...,...,...,...,...
7813,England,Australia,Melbourne,95,32,4,6.477273,25.0
32511,West Indies,New Zealand,Auckland,143,38,4,10.463415,53.0
5192,England,Pakistan,London,158,17,5,9.203883,43.0
12172,New Zealand,South Africa,Durban,67,74,10,8.739130,54.0
33003,New Zealand,Pakistan,Dubai,95,28,6,6.195652,35.0

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_absolute_error

In [13]:
trf=ColumnTransformer([
    ('trf',OneHotEncoder(sparse_output=False,drop='first'),['batting_team','bowling_team','city'])],
                      remainder='passthrough')

In [14]:
# we make pipeline that handles all columns.
pipe=Pipeline(steps=[
    ('step1',trf),
    ('step2',StandardScaler()),
    ('step3',XGBRegressor(n_estimators=1000,learning_rate=0.2,max_depth=12,random_state=1))
])

In [15]:
#Training  training data over algorithm 
pipe.fit(X_train,Y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', StandardScaler()),
                ('step3',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=None, device=None...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.2,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=12, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=1000, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [18]:
#prediction over testing data
Y_pred=pipe.predict(X_test)

In [19]:
#Regression metrics value

In [21]:
print(r2_score(Y_test,Y_pred))
print(mean_absolute_error(Y_test,Y_pred))

0.9877704977989197
1.6343241930007935

In [30]:
#Exporting model
import pickle

In [31]:
pickle.dump(pipe,open('pipe.pkl','wb'))